# Generated by Django 2.2.1 on 2019-08-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_home_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.TextField(max_length=400)),
                ('text2', models.TextField(max_length=500)),
            ],
        ),
    ]
