# Generated by Django 2.2.1 on 2019-08-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_texthome'),
    ]

    operations = [
        migrations.AddField(
            model_name='texthome',
            name='text1_h',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='texthome',
            name='text2_h',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
    ]
