# Generated by Django 2.2.1 on 2019-08-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20190831_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texthome',
            name='text1_h',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='texthome',
            name='text2_h',
            field=models.CharField(default='', max_length=200),
        ),
    ]
